
server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000

websocket:
  endpoint: /gs-guide-websocket
  redis:
    host: ${spring.data.redis.host}
    port: ${spring.data.redis.port}
logging:
  level:
    com.cloudx: debug
