
# OpenFeign 启动配置
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            # 连接超时
            connect-timeout: 200
            # socket超时
            read-timeout: 3000
        # 开启断路器
        circuitbreaker:
          enabled: true
        # 开启okhttp
        okhttp:
          enabled: true
        # 开启压缩
        compression:
          request:
            enabled: true
            min-request-size: 1024
          response:
            enabled: true